### PR TITLE
 	change repository to stable, remove salt-latest component

### PR DESCRIPTION
**Pull request by smolaon**

### CODE REVIEW

**Comment by pupapaik** [comment]
yes

**Comment by roman-verchikov** [comment]
In my environment this change resulted in salt-minion of version 2015.8.8 installed:
```
salt-minion --version
salt-minion 2015.8.8 (Beryllium)
```
So I would refrain from merging it

**Review by epcim — APPROVED** [review]

**Comment by epcim** [comment]
salt may be preinstalled or will be installed by the salt bootstrap script (as a part of salt master setup sh) as we want to be able to specify specific version by salt bootstrap script (bootstrap.saltstack.com), that only works with saltstack upstream repos (according a doc) usage of salt-latest component is really an alternative.


make sure you provide enough parameters for saltstack bootstrap script so he really installs correct version.

**Comment by roman-verchikov** [comment]
@epcim according to MCP deployment guide salt *MUST* be installed with this script, not with bootstrap.sh or anything else. By merging this change you introduce yet another inconsistency between *official* documentation and actual steps required to achieve desired state which is not documented anywhere. The patch must be rolled back or documentation must be changed accordingly.

**Comment by epcim** [comment]
sure, the script is the valid still.i am not talking about an bootsteap.sh but the bootstrap.saltstack.com that is called at the -init.sh inside system_config ().note - the scrips are kind of evaluation to proof it could work this way. I am now starting work on a botstrap salt formula. that will do the job hopefully even better.On 5 May 2017 20:07, Roman Verchikov <notifications@github.com> wrote:@epcim according to MCP deployment guide salt MUST be installed with this script, not with bootstrap.sh or anything else. By merging this change you introduce yet another inconsistency between official documentation and actual steps required to achieve desired state which is not documented anywhere. The patch must be rolled back or documentation must be changed accordingly.

**Pull request merged**
